# Generated by Django 4.1.1 on 2022-09-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VesselPositionsLastRetrieved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('website', models.CharField(max_length=255, null=True)),
                ('mmsi', models.IntegerField(null=True)),
                ('position_received_on', models.DateTimeField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('boat_type', models.IntegerField(null=True)),
                ('heading', models.IntegerField(null=True)),
                ('speed', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'mmsi')},
            },
        ),
    ]
