# Generated by Django 4.1.1 on 2022-09-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='tracking_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
