# Generated by Django 4.1.1 on 2022-09-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0002_vessel_tracking_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='heading',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='speed',
            field=models.FloatField(null=True),
        ),
    ]
