# Generated by Django 4.1.1 on 2022-09-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0003_alter_vessel_heading_alter_vessel_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='website',
        ),
    ]
