# Generated by Django 4.1.1 on 2022-09-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0004_remove_vessel_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='name',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='tracking_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
