# Generated by Django 4.1.1 on 2022-09-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0005_alter_vessel_name_alter_vessel_tracking_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='tracking_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
