# Generated by Django 4.1.1 on 2022-09-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0006_alter_vessel_tracking_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='boat_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='heading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='mmsi',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='position_received_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
