# Generated by Django 4.1.1 on 2022-09-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0007_alter_vessel_boat_type_alter_vessel_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='make_and_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
