# Generated by Django 4.1.1 on 2022-09-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0008_vessel_make_and_model_vessel_year_built'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='privacy_mode',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
