# Generated by Django 4.1.1 on 2022-09-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_vessel'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=100, null=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='member',
            name='website',
            field=models.CharField(max_length=255, null=True, verbose_name='website'),
        ),
    ]
