# Generated by Django 4.1.1 on 2022-09-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_phone_number_member_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='facebook_url',
            field=models.CharField(max_length=255, null=True, verbose_name='facebook_url'),
        ),
        migrations.AddField(
            model_name='member',
            name='instagram_url',
            field=models.CharField(max_length=255, null=True, verbose_name='instagram url'),
        ),
    ]
